### PR TITLE
Allow https connections

### PR DESCRIPTION
**Pull request by james-portman**

### CODE REVIEW

**Comment by bcicen** [comment]
thanks @james-portman; is `stats.py` intended to be included in this commit?

**Comment by james-portman** [comment]
Hello,
no it wasn't sorry, I think I pushed it over the top of the branch I PR'd to you sorry.
Just the first commit would do..
https://github.com/bcicen/haproxy-stats/pull/6/commits/e2bf70a587addbec4c94b5211ae07ee0bbbe0608

Cheers

**Comment by bcicen** [comment]
thanks for the follow-up. commit merged and included in latest version.

**Comment by james-portman** [comment]
Awesome, thank you!

**Pull request closed without merging**
